name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Check code style
        run: |
          pip install flake8
          flake8 app tests --count --show-source --statistics

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: imzerocool/currency-converter:v1.2.${{ github.run_number }}

      - name: Update Helm chart version and image tag
        run: |
          echo "Updating Helm chart version and image tag"
          sed -i "s/^version: .*/version: v1.2.${{ github.run_number }}/" helm/currency-converter/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"1.2.${{ github.run_number }}\"/" helm/currency-converter/Chart.yaml
          sed -i "s|^  tag: .*|  tag: v1.2.${{ github.run_number }}|" helm/currency-converter/values.yaml

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push updated Helm chart
        run: |
          git add helm/currency-converter/Chart.yaml helm/currency-converter/values.yaml
          git commit -m "Update Helm chart to v1.2.${{ github.run_number }}"
          git push origin develop

  tag-on-main-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v3

      - name: Create and push Git tag
        run: |
          git tag v1.2.${{ github.run_number }}
          git push origin v1.2.${{ github.run_number }}