name: CI/CD

on:
  push:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: check code style
        run: |
          pip install flake8
          flake8 app tests --count --show-source --statistics
   
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' 
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: imzerocool/currency-converter:v1.2.${{ github.run_number }}

      - name: update the helm chart version and image tag
        run: |
          echo "Updating helm chart version and image tag"
          sed -i "s/^version: .*/version: v1.2.${{ github.run_number }}\n/" helm/currency-converter/Chart.yaml
          sed -i "s/^appVersion: .*/appVersion: \"1.2.${{ github.run_number }}\"/" helm/currency-converter/Chart.yaml
          sed -i "s|^  tag: .*|  tag: v1.2.${{ github.run_number }}|" helm/currency-converter/values.yaml
          cat helm/currency-converter/Chart.yaml
          cat helm/currency-converter/values.yaml
